import 'package:flutter/foundation.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:uuid/uuid.dart';
import '../models/shopping_model.dart';
import '../models/inventory_model.dart';

class ShoppingProvider extends ChangeNotifier {
  static const _boxName = 'shoppingBox';
  late Box<ShoppingItem> _box;
  bool _initialized = false;

  List<ShoppingItem> get items => _box.values.toList()
    ..sort((a, b) {
      if (a.isPurchased != b.isPurchased) {
        return a.isPurchased ? 1 : -1;
      }
      return a.name.compareTo(b.name);
    });

  List<ShoppingItem> get pending =>
      items.where((i) => !i.isPurchased).toList();

  List<ShoppingItem> get purchased =>
      items.where((i) => i.isPurchased).toList();

  List<ShoppingItem> get autoItems =>
      items.where((i) => i.isAutoGenerated).toList();

  List<ShoppingItem> get manualItems =>
      items.where((i) => !i.isAutoGenerated).toList();

  Future<void> init() async {
    if (_initialized) return;
    _box = await Hive.openBox<ShoppingItem>(_boxName);
    _initialized = true;
    notifyListeners();
  }

  Future<void> addItem(ShoppingItem item) async {
    await _box.put(item.id, item);
    notifyListeners();
  }

  Future<void> togglePurchased(String id) async {
    final item = _box.get(id);
    if (item == null) return;
    item.isPurchased = !item.isPurchased;
    await _box.put(id, item);
    notifyListeners();
  }

  Future<void> deleteItem(String id) async {
    await _box.delete(id);
    notifyListeners();
  }

  Future<void> clearPurchased() async {
    final purchased = _box.values.where((i) => i.isPurchased).toList();
    for (final item in purchased) {
      await _box.delete(item.id);
    }
    notifyListeners();
  }

  /// Sync auto-generated items based on current low-stock inventory.
  Future<void> syncFromInventory(List<InventoryItem> lowStockItems) async {
    // Remove old auto items that are no longer low stock
    final existingAutoIds = _box.values
        .where((i) => i.isAutoGenerated && i.linkedInventoryId != null)
        .map((i) => i.linkedInventoryId!)
        .toSet();

    final lowStockIds = lowStockItems.map((i) => i.id).toSet();

    // Remove auto items for items that are no longer low stock
    final toRemove = _box.values
        .where((i) =>
            i.isAutoGenerated &&
            i.linkedInventoryId != null &&
            !lowStockIds.contains(i.linkedInventoryId) &&
            !i.isPurchased)
        .toList();
    for (final item in toRemove) {
      await _box.delete(item.id);
    }

    // Add new auto items for newly low stock items
    for (final invItem in lowStockItems) {
      final alreadyExists = _box.values.any(
          (s) => s.linkedInventoryId == invItem.id && s.isAutoGenerated);
      if (!alreadyExists) {
        final needed =
            (invItem.minimumThreshold * 2 - invItem.quantity).clamp(1, 999);
        final item = ShoppingItem(
          id: const Uuid().v4(),
          name: invItem.name,
          quantityNeeded: needed.toDouble(),
          unit: invItem.unitLabel,
          isAutoGenerated: true,
          linkedInventoryId: invItem.id,
        );
        await _box.put(item.id, item);
      }
    }
    notifyListeners();
  }

  ShoppingItem createManualItem({
    required String name,
    required double quantityNeeded,
    String unit = 'pcs',
  }) {
    return ShoppingItem(
      id: const Uuid().v4(),
      name: name,
      quantityNeeded: quantityNeeded,
      unit: unit,
      isAutoGenerated: false,
    );
  }

  Future<Map<String, dynamic>> exportData() async {
    return {
      'shopping': _box.values
          .map((s) => {
                'id': s.id,
                'name': s.name,
                'quantityNeeded': s.quantityNeeded,
                'unit': s.unit,
                'isAutoGenerated': s.isAutoGenerated,
                'isPurchased': s.isPurchased,
                'linkedInventoryId': s.linkedInventoryId,
                'createdAt': s.createdAt.toIso8601String(),
              })
          .toList(),
    };
  }

  Future<void> importData(List<dynamic> data) async {
    await _box.clear();
    for (final item in data) {
      final s = ShoppingItem(
        id: item['id'],
        name: item['name'],
        quantityNeeded: (item['quantityNeeded'] as num).toDouble(),
        unit: item['unit'] ?? 'pcs',
        isAutoGenerated: item['isAutoGenerated'] ?? false,
        isPurchased: item['isPurchased'] ?? false,
        linkedInventoryId: item['linkedInventoryId'],
        createdAt: DateTime.parse(item['createdAt']),
      );
      await _box.put(s.id, s);
    }
    notifyListeners();
  }

  Future<void> clearAll() async {
    await _box.clear();
    notifyListeners();
  }
}
