import 'package:hive/hive.dart';

part 'shopping_model.g.dart';

@HiveType(typeId: 7)
class ShoppingItem extends HiveObject {
  @HiveField(0)
  String id;

  @HiveField(1)
  String name;

  @HiveField(2)
  double quantityNeeded;

  @HiveField(3)
  String unit;

  @HiveField(4)
  bool isAutoGenerated;

  @HiveField(5)
  bool isPurchased;

  @HiveField(6)
  String? linkedInventoryId;

  @HiveField(7)
  DateTime createdAt;

  ShoppingItem({
    required this.id,
    required this.name,
    required this.quantityNeeded,
    this.unit = 'pcs',
    this.isAutoGenerated = false,
    this.isPurchased = false,
    this.linkedInventoryId,
    DateTime? createdAt,
  }) : createdAt = createdAt ?? DateTime.now();

  ShoppingItem copyWith({
    String? id,
    String? name,
    double? quantityNeeded,
    String? unit,
    bool? isAutoGenerated,
    bool? isPurchased,
    String? linkedInventoryId,
  }) {
    return ShoppingItem(
      id: id ?? this.id,
      name: name ?? this.name,
      quantityNeeded: quantityNeeded ?? this.quantityNeeded,
      unit: unit ?? this.unit,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      isPurchased: isPurchased ?? this.isPurchased,
      linkedInventoryId: linkedInventoryId ?? this.linkedInventoryId,
      createdAt: createdAt,
    );
  }
}
